//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StripConsentModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StripConsentModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataSubmissionSpecification xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;PatientFiles&gt;
        ///    &lt;File xsi:type=&quot;RegistryFile&quot;&gt;
        ///      &lt;Name&gt;patient.*\.csv&lt;/Name&gt;
        ///      &lt;Fields&gt;
        ///        &lt;Field&gt;
        ///          &lt;Name&gt;NHS Number&lt;/Name&gt;
        ///          &lt;DataItemCode&gt;IBD01&lt;/DataItemCode&gt;
        ///          &lt;Version&gt;2015_H&lt;/Version&gt;
        ///          &lt;Group&gt;PATIENT: Identifiers&lt;/Group&gt;
        ///        &lt;/Field&gt;
        ///        &lt;Field&gt;
        ///          &lt;Name&gt;Date of birth&lt;/Name&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2021_K_IBD_Registry_Submission_Dataset_V01__Nov_2021_ {
            get {
                return ResourceManager.GetString("_2021_K_IBD_Registry_Submission_Dataset_V01__Nov_2021_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Subitems,Version,Site Name,IBD Audit Code,Trust/Health Board,Trust/Health Board IBD Code,IBD Service,Service IBD Code,Source,Source - SM,Auto Number,Adult/Paeds,Country,Clinical System,WebTool Use,Grant,NDA,IBD Sub-site code,ODS code,ODS Level,Registry 2020,Agrs 2020,QA 2021-22,Postcode,Finance breakdown 20-21,Quality Accounts,QA 2019-20
        ///#staustell,,IBDR ARCHIVED,St Austell Community Hospital,IBD929,Cornwall Partnership NHS Foundation Trust,IBD738,St Austell Community Hospital,IBD449,ARCHIVE (ABH),ADD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiteMaster {
            get {
                return ResourceManager.GetString("SiteMaster", resourceCulture);
            }
        }
    }
}
